create table if not exists jobs_raw_mantiks (
  id bigint generated by default as identity primary key,
  external_id text,
  company text,
  company_domain text,
  title text,
  description text,
  location_name text,
  location_id bigint,
  seniority text,
  posted_at timestamptz,
  source text,
  url text,
  fetched_at timestamptz default now(),
  unique (company_domain, external_id)
);

create table if not exists jobs_norm (
  id text primary key,
  title text not null,
  company text not null,
  company_domain text,
  location_name text,
  location_id bigint,
  posted_at timestamptz,
  seniority text,
  source text,
  url text,
  track text check (track in ('consulting','finance','strategy','operations','marketing','product','data','sustainability','other')),
  score int check (score between 0 and 100),
  created_at timestamptz default now()
);

create index if not exists idx_jobs_raw_mantiks_company_domain on jobs_raw_mantiks(company_domain);
create index if not exists idx_jobs_raw_mantiks_posted_at on jobs_raw_mantiks(posted_at);
create index if not exists idx_jobs_norm_score on jobs_norm(score);
create index if not exists idx_jobs_norm_track on jobs_norm(track);


