// ✅ Shared Location Configuration for All Scrapers

export const TARGET_CITIES = [
  'Dublin, Ireland',
  'London, United Kingdom', 
  'Berlin, Germany',
  'Amsterdam, Netherlands',
  'Paris, France',
  'Munich, Germany',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Stockholm, Sweden',
  'Zurich, Switzerland',
  'Copenhagen, Denmark',
  'Vienna, Austria',
  'Brussels, Belgium',
  'Prague, Czech Republic',
  'Warsaw, Poland',
  'Milan, Italy',
  'Rome, Italy',
  'Lisbon, Portugal',
  'Athens, Greece'
];

export const EU_COUNTRIES = [
  'Ireland',
  'United Kingdom', 
  'Germany',
  'Netherlands',
  'France',
  'Spain',
  'Sweden',
  'Switzerland',
  'Denmark',
  'Austria',
  'Belgium',
  'Czech Republic',
  'Poland',
  'Italy',
  'Portugal',
  'Greece',
  'Finland',
  'Norway',
  'Luxembourg',
  'Malta',
  'Cyprus',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Slovenia',
  'Slovakia',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Croatia'
];

// City to country mapping for quick lookups
export const CITY_COUNTRY_MAP: Record<string, string> = {
  'Dublin': 'Ireland',
  'London': 'United Kingdom',
  'Berlin': 'Germany',
  'Munich': 'Germany',
  'Amsterdam': 'Netherlands',
  'Paris': 'France',
  'Madrid': 'Spain',
  'Barcelona': 'Spain',
  'Stockholm': 'Sweden',
  'Zurich': 'Switzerland',
  'Copenhagen': 'Denmark',
  'Vienna': 'Austria',
  'Brussels': 'Belgium',
  'Prague': 'Czech Republic',
  'Warsaw': 'Poland',
  'Milan': 'Italy',
  'Rome': 'Italy',
  'Lisbon': 'Portugal',
  'Athens': 'Greece'
};

// Language hints for each city (for multilingual keyword selection)
export const CITY_LANGUAGE_MAP: Record<string, string[]> = {
  'Dublin': ['en'],
  'London': ['en'],
  'Berlin': ['de', 'en'],
  'Munich': ['de', 'en'],
  'Amsterdam': ['nl', 'en'],
  'Paris': ['fr', 'en'],
  'Madrid': ['es', 'en'],
  'Barcelona': ['es', 'en'],
  'Stockholm': ['sv', 'en'],
  'Zurich': ['de', 'en'],
  'Copenhagen': ['da', 'en'],
  'Vienna': ['de', 'en'],
  'Brussels': ['fr', 'nl', 'en'],
  'Prague': ['cs', 'en'],
  'Warsaw': ['pl', 'en'],
  'Milan': ['it', 'en'],
  'Rome': ['it', 'en'],
  'Lisbon': ['pt', 'en'],
  'Athens': ['el', 'en']
};
